name: Deploy to QA

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push frontend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/csc424-final-exam-frontend:latest ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/csc424-final-exam-frontend:latest

      - name: Build and push backend
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/csc424-final-exam-backend:latest ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/csc424-final-exam-backend:latest

      - name: Build and push nginx
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/csc424-final-exam-nginx:latest ./nginx
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/csc424-final-exam-nginx:latest

      - name: Deploy
        run: |
          docker compose down
          docker compose pull
          docker compose up -d
